### ISSUE TITLE
Usage counter

### ISSUE THREAD

**Issue by ghost** [enanomapper/nano-lazar#2]
Please consider adding an usage counter (like Google Analytics or
keep local logs) so that we can monitor the uptake. For our market
analysis ("sustainability") it would be really useful 1. where it is
being used (countries, domains), 2. how they are using it (harder, but
doable...)

**Comment by rautenberg** [comment]
A Google Analytics account has been created with an web property ID for nano-lazar.in-silico.ch. Java Script for Analytics is loaded in layout.haml
